### ISSUE TITLE
create, modify and destroy pane

### ISSUE THREAD

**Issue by ilyaminati** [rstudio/rstudioapi#38]
In an addin, I'd like to create a pane in RStudio, populate it with custom content (e.g., HTML or a Shiny app), modify the content on request, and destroy the panel on request.

**Comment by hadley** [comment]
For security reasons, we can't allow arbitrary html content, so this is out of scope for rstudioapi.

**Comment by ilyaminati** [comment]
The API already allows me to display arbitrary HTML content with `rstudioapi::viewer()`. 

This request is more accurately about creating, modifying and destroying panes.

**Comment by saurfang** [comment]
I also would like provide a use case where this is particularly useful.

I have a locally hosted web app that monitors some execution progress (e.g. concurrently long-running SQL queries). 

It would be useful to show this informative view when the user starts a long-running task but immediately closes the viewer (restore to previous content/URL) when the computation finishes. (e.g. the user might be using viewer pane to preview an RMarkdown document)

In addition, because this monitor tracks the progress of multiple running processes, it incrementally loads new progress and it is a bad user experience if the `view(<url>)` is called everytime a new execution initiated, where the entire page would reload.

--------------

I think all it takes is to make `rstudioapi::viewer()` to return currently browsing UR. Maybe `rstudioapi::viewer(NULL)` would terminate viewer (assume `rstudioapi::viewer()` returns `NULL` if viewer pane is not in use for API consistency).

This would work great for my use case. @ilyaminati's use case can use a Shiny app or whatever mechanism to drive the update of the content. I think biggest pain point of current API is that we always have to reload the entire viewer pane even for an incremental content update.
