### ISSUE TITLE
rstudioapi::hasFun("debugSource") returns FALSE

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudioapi#4]
even though it is available.

**Comment by jjallaire** [comment]
That's because debugSource is actually not part of the `.rs.api.` family of functions (it doesn't have a "hidden" prefix like the other `.rs.` functions because we emit it to the console, we have a number of functions like this). I guess we could either add an alias to it is `.rs.api.debugSource` or we could also search for `tools:rstudio:::debugSource` along with `tools::rstudio:::.rs.api.debugSource`.

**Comment by hadley** [comment]
It's not a big deal for me - I thought it might be nice to use in testthat (so that you could more nicely debug tests), but in most cases the test are run in a separate R process so it doesn't actually help.
